### ISSUE TITLE
Save State 

### ISSUE THREAD

**Issue by btwq** [singer-io/getting-started#39]
In Step 5 the suggested Save State lines to execute:

> › tap-fixerio --state state.json | target-gsheet -c config.json >> state.json
> › tail -1 state.json > state.json.tmp && mv state.json.tmp state.json
> (rinse and repeat)

I tried instead a single ">": 

› tap-fixerio --state state.json | target-gsheet -c config.json > state.json

Logically this should simply overwrite an existing state file. Instead I encounter: 

> /var/www# tap-fixerio/bin/tap-fixerio --state state.fixerio.json | target-gsheet/bin/target-gsheet -c config.json > state.fixerio.json
> Traceback (most recent call last):
>   File "tap-fixerio/bin/tap-fixerio", line 11, in <module>
>     sys.exit(main())
>   File "/var/www/tap-fixerio/lib/python3.5/site-packages/tap_fixerio.py", line 101, in main
>     state = json.load(file)
>   File "/usr/lib/python3.5/json/__init__.py", line 268, in load
>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>   File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Am I missing something here? It would be easier to have one line than the "rinse and repeat" method

**Comment by cmerrick** [comment]
`>` will wipe out the contents of the prior file before any of the processes start.
