### ISSUE TITLE
Add an official statement regarding loose version requirements

### ISSUE THREAD

**Issue by timvisher** [singer-io/getting-started#47]
This comes up enough (see https://github.com/singer-io/target-csv/pull/10, https://github.com/singer-io/singer-python/issues/80, https://github.com/singer-io/singer-tools/issues/8, https://github.com/singer-io/target-csv/issues/13, etc.) that I think we should finally write something down about it.

**Comment by luandy64** [comment]
Added a [section](https://github.com/singer-io/getting-started/blob/master/docs/BEST_PRACTICES.md#dependency-versioning) to best practices about dependency versioning: 

Also added a [FAQ](https://github.com/singer-io/getting-started/blob/master/docs/FAQ.md) page with an answered question about running taps & targets in separate virtual envs.
