### ISSUE TITLE
How do I submit a tap for inclusion in Stitch?

### ISSUE THREAD

**Issue by chrisgoddard** [singer-io/getting-started#52]
Hey there!

I'm developing a tap for BigCommerce here https://github.com/chrisgoddard/tap-bigcommerce

What is the process for getting new taps integrated in Stitch? This is my first one but I have 3-4 other platforms that I want to write taps for and ideally have available as Stitch connectors.

Thanks.

-Chris

**Comment by dylan-stitch** [comment]
Hey @chrisgoddard ,

Any community built integrations can be submitted by their creator to Stitch for review and potential inclusion in Stitch as a Community Integration using [this form](https://docs.google.com/forms/d/e/1FAIpQLSdjuB3jrsuCoK5juLVvFzSPMLrxP5Wz_Xy1Fy5yVhP748bg8w/viewform?usp=send_form)
